name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
       submodules: true

    - name: Install dependencies
      run: sudo apt-get install libfmt-dev libglm-dev libgdal-dev catch2 libfreeimage-dev libtbb-dev
      
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DATB_UNITTESTS_EXTENDED=OFF

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target terrainbuilder -j 18
      
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
       submodules: true

    - name: Install dependencies
      run: sudo apt-get install libfmt-dev libglm-dev libgdal-dev catch2 libfreeimage-dev libtbb-dev
      
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target unittests_terrainlib -j 8
    
    - uses: actions/cache@v3
      id: terrain_builder_unittest_data
      with:
        path: ./unittests/data
        key: terrain_builder_unittest_data.tar.gz
  
    - name: Download data
      if: steps.cache.outputs.cache-hit != 'true'
      run: wget -qO- https://gataki.cg.tuwien.ac.at/raw/terrain_builder_unittest_data.tar.gz | tar xvz -C ./unittests/

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ./unittests/unittests_terrainlib

